import './assets/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'next, nextjs, create next app',
};

const MainLayout = ({ children }) => {
  return (
    <html>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
};

export default MainLayout;

